/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    carousel: Carousel;
    specification: Specification;
    cars: Car;
    bodyStyle: BodyStyle;
    brand: Brand;
    "about-us": AboutUs;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  locale: null;
  user: User & {
    collection: "users";
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  firstName: string | null;
  lastName: string | null;
  phone: string | null;
  companyName?: string;
  address: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  agreeMarketingEmails: boolean;
  terms: boolean;
  role: "user" | "admin";
}

export interface Car {
  id: string;
  productid: string;
  carName: string;
  brand: string | Brand;
  coverImage: string | Media;
  availability?: boolean | null;
  make: string;
  arrivalDate?: string | null;
  engine?: string | null;
  transmission?: string | null;
  interior?: string | null;
  exterior?: string | null;
  fuel?: string | null;
  drive?: string | null;
  bodyStyle: string;
  price: string;
  /**
   * Choose the relevant specifications for this product.
   */
  specifications: (string | Specification)[];
  gallery?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
export interface Carousel {
  id: string;
  image: string | Media;
  title: string;
  updatedAt: string;
  createdAt: string;
}

export interface Specification {
  id: string;
  specification: string;
  updatedAt: string;
  createdAt: string;
}

export interface BodyStyle {
  id: string;
  style: string;
  logo: string; // This is the ID of the uploaded media file
  createdAt: string;
  updatedAt: string;
}

export interface Brand {
  id: string;
  brand: string;
  models?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  logo: string | Media;
  updatedAt: string;
  createdAt: string;
}

export interface AboutUs {
  id: string;
  "about-us": string;
  "core-values": {
    name: string;
    icon: string | Media;
    id?: string | null;
  }[];
  "our-mission": string;
  vision: string;
  "our-services": {
    service: string;
    id?: string | null;
  }[];
  "tailored-services": {
    service: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: "users";
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
